### PR TITLE
export map object to property

### PR DESCRIPTION
**Pull request by wilds**
Now is possible to get openlayers map from javascript:
var map = $("#ol3map").prop("map");

### CODE REVIEW

**Comment by Styp** [comment]
@mhosio : What do you think? I prefere not to do some low-level hacks on JS. I like the way we do it now with getter and setter and everything mapped to an object.

What do you think?

**Comment by wilds** [comment]
This is the only way I found to add a tooltip on a vector feature (marker on map).
Adding a js file to the UI, I can have the tooltips like these: http://openlayers.org/en/latest/examples/kml-earthquakes.html

**Comment by Styp** [comment]
Can you provide a sample in the test application? I am willing to merge this, but would like to see a use case ;)

**Comment by mhosio** [comment]
I don't have anything against adding the map object as element property to the map element. But the map element should not have static id since there might be several maps on the same page. Suggest that you just set the id explicitly by using the server side api that is already there.

**Comment by wilds** [comment]
Test case:
https://github.com/wilds/v-ol3-demo/tree/master/src/main/java/org/vaadin

**Pull request closed without merging**
