### PR TITLE
Add LayerSwitcher control

### PR DESCRIPTION
**Pull request by markathomas**
Added support for a LayerSwitcher control based on code from https://github.com/walkermatt/ol3-layerswitcher.

### CODE REVIEW

**Comment by Styp** [comment]
Sorry for letting you wait. Matti will have a look at it soon I hope.
thanks for being patient with us :)

**Comment by markathomas** [comment]
Sure, no problem at all.

**Comment by Styp** [comment]
Hi @markathomas 

I merged the files into the master. As this is a collaboration project started at Vaadin and @mhosio has the lead. I would appreciate it you could sign the contribution agreement.

https://vaadin.com/wiki/-/wiki/Main/Contributing+Code / step 1 only

Thank you.
Martin

P.s. @mhosio in worst case we have to revert it - I realized it to late, that he has not signed the agreement so far...

**Comment by markathomas** [comment]
I have no problem signing the agreement. I'll do so at my earliest
convenience.

**Comment by markathomas** [comment]
I've added the contributor agreement to my profile.  Username is mthomas

**Comment by Styp** [comment]
nice! Thank you!

**Pull request closed without merging**
