### PR TITLE
Maybe it will be interesting

### PR DESCRIPTION
**Pull request by iSergio**
In my planes, realize all events and listeners, all controls and all interactions.

### CODE REVIEW

**Comment by Styp** [comment]
I will have a look at it.
Is it possible that you provide us with some 'example' code like the other examples, that already exist?

**Comment by mhosio** [comment]
The pull request contains code for the gwt-module. I suppose we could come up with the tests / examples as soon as we implement the vaadin-side wrappers for that. 

But since all the add-on contributors have signed the Vaadin contribution agreement, I would like to keep it that way. Would it be possible to sign the contribution agreement (electronically) before we merge the code? 

https://vaadin.com/wiki/-/wiki/Main/Contributing+Code / step 1 only

**Comment by iSergio** [comment]
I'll try on this weekend. Examples how use i can include into description of Java classes

**Comment by mhosio** [comment]
Can't wait to merge your contribution in. Excellent work, iSergio!

**Comment by iSergio** [comment]
I signed the Vaadin contribution agreement

**Comment by mhosio** [comment]
Big Thank you for your contribution, iSergio! The changes look good to me but I'll leave it to Mr. Stypinski to do the final review and merge. Really useful additions to the client-side part of the add-on.

**Comment by Styp** [comment]
Merged and partialy tested - Thanks!
That looks awesome!

**Pull request closed without merging**
